---
name: Bug Report
description: Use this template to report a bug  # Changed from 'about'
title: "[BUG] Descriptive bug title"
labels: [bug]  # Array format recommended
assignees: []  # Must be array (empty array instead of empty string)
body:
  - type: markdown
    attributes:
      value: "## Bug Report\n\nPlease fill in the following details to help us resolve the issue quickly!"
  - type: input
    id: bug_title
    attributes:
      label: "Bug Summary"
      description: "Provide a brief summary of the bug."
      placeholder: "e.x. The application crashes on startup."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps needed to reproduce the bug in detail from start to end."
      value: "1. \n2. \n3. "  # Must be non-empty string
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected_vs_actual
    attributes:
      label: "Expected vs Actual Behavior"
      description: "What did you expect to happen? What actually happened?"
      placeholder: "Expected: The app loads successfully.\nActual: The app crashes with an error message."
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: "Select the environment where the bug occurs."
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: checkboxes
    id: bug_impact
    attributes:
      label: "Bug Impact"
      description: "Select all that apply."
      options:
        - label: Critical (application unusable)
        - label: Major (significant issue but not blocking)
        - label: Minor (small issue, not a priority)
  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Add any other details, logs, or screenshots that may help."
      placeholder: "Attach logs or screenshots here."
      value: " "  # Non-empty placeholder value
